"""Comment Table Addons

Revision ID: 4d79e5ff1d96
Revises: ff50f31c9f3d
Create Date: 2022-04-16 08:27:50.118147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d79e5ff1d96'
down_revision = 'ff50f31c9f3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("comments_user_id_users_data", 'users_data', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint("comments_user_id_users_data", type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
