"""another migration

Revision ID: 6d25f1e7dc8d
Revises: 83c52b3e9d21
Create Date: 2022-04-15 12:54:30.515415

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6d25f1e7dc8d'
down_revision = '83c52b3e9d21'
branch_labels = None
depends_on = None

convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("blog_posts_user_id_users_data", 'users_data', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_constraint('blog_posts_user_id_users_data', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
