"""initial migration'

Revision ID: 83c52b3e9d21
Revises: 
Create Date: 2022-04-15 12:49:11.855890

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '83c52b3e9d21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_constraint('blog_posts_user_id_users_data', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('blog_posts_user_id_users_data', 'users_data', ['user_id'], ['id'])

    # ### end Alembic commands ###
