"""comments-posts relationship

Revision ID: f4fbe3d03cee
Revises: 4d79e5ff1d96
Create Date: 2022-04-16 08:46:32.919117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4fbe3d03cee'
down_revision = '4d79e5ff1d96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("comments_post_id_blog_posts", 'blog_posts', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint("comments_post_id_blog_posts", type_='foreignkey')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
